// Configuration
export const CONFIG = {
  maxFileSizeMB: 1,
  maxTotalSizeMB: 50,
  maxDepth: 10,
  rateLimitThreshold: 100,
  includeExtensions: [
    ".js",
    ".ts",
    ".jsx",
    ".tsx",
    ".py",
    ".java",
    ".cpp",
    ".c",
    ".cs",
    ".php",
    ".rb",
    ".go",
    ".rs",
    ".swift",
    ".kt",
    ".html",
    ".css",
    ".vue",
    ".scss",
    ".sass",
    ".less",
    ".json",
    ".yaml",
    ".yml",
    ".xml",
    ".sql",
    ".sh",
  ],
  excludePatterns: [
    "node_modules/",
    "dist/",
    "build/",
    ".git/",
    "coverage/",
    "vendor/",
    "target/",
    "__pycache__/",
    ".venv/",
    "venv/",
    ".DS_Store",
    ".gradle/",
    ".mvn/",
    "Thumbs.db",
    ".env",
  ],
};

// Get language from extension
export function getLanguage(extension: string): string {
  const langMap: Record<string, string> = {
    ".js": "JavaScript",
    ".ts": "TypeScript",
    ".jsx": "JavaScript",
    ".tsx": "TypeScript",
    ".py": "Python",
    ".java": "Java",
    ".cpp": "C++",
    ".c": "C",
    ".cs": "C#",
    ".php": "PHP",
    ".rb": "Ruby",
    ".go": "Go",
    ".rs": "Rust",
    ".swift": "Swift",
    ".kt": "Kotlin",
    ".html": "HTML",
    ".css": "CSS",
    ".vue": "Vue",
    ".scss": "SCSS",
    ".sass": "Sass",
    ".less": "Less",
    ".json": "JSON",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".xml": "XML",
    ".sql": "SQL",
    ".sh": "Shell",
  };
  return langMap[extension] || "Other";
}
